---
include:
  # corne
  # left
  - board: nice_nano_v2
    shield: corne_left_peripheral
    snippet: common-config
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: corne_left_peripheral

  # right
  - board: nice_nano_v2
    shield: corne_right
    snippet: common-config
    artifact-name: corne_right_peripheral

  # dongle
  - board: nice_nano_v2
    shield: corne_dongle dongle_display
    snippet: common-config studio-rpc-usb-uart
    artifact-name: corne_dongle


    
  # reset
  - board: nice_nano_v2
    shield: settings_reset
