# ZMK Corne - Manifesto West Padrão
# Documentação: https://zmk.dev/docs/config
#
# Configuração mínima usando apenas o ZMK oficial

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: redmasters
      url-base: https://github.com/redmasters

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: scyan-zmk-module
      remote: redmasters
      revision: 1088d0577ea486a55cecf0af682afd3e1c504d14

  self:
    path: config
