# ZMK Corne - Manifesto West Padrão
# Documentação: https://zmk.dev/docs/config
#
# Configuração mínima usando apenas o ZMK oficial

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: redmasters
      url-base: https://github.com/redmasters

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: scyan-zmk-module
      remote: redmasters
      revision: 06cf4ef7dd0778e803266fcd76ee3d44ac49f49b

  self:
    path: config
